Repository ProEpiDesenvolvimento/guardioes-web, pull requests merged in 2020-10, with the labels that each got.

#98 Creates the Groups page
  src/actions/index.js
  src/constants/action-types.js
  src/pages/Home/components/ContentBox/index.js
  src/pages/Home/components/Contents/index.js
  src/pages/Home/components/GroupManagers/index.js
  src/pages/Home/components/Groups/index.js
  src/pages/Home/components/Groups/services/createGroup.js
  src/pages/Home/components/Groups/services/deleteGroup.js
  src/pages/Home/components/Groups/services/editGroup.js
  src/pages/Home/components/Groups/services/getAllGroups.js
  src/pages/Home/components/Groups/styles.js
  src/pages/Home/components/Managers/index.js
  src/pages/Home/components/NavBar/index.js
  src/pages/Home/components/Symptoms/index.js
  src/pages/Home/index.js
  src/pages/PreRegister/Form/services/validateCnpj.js
  src/reducers/user.js
  src/sharedComponents/Header/index.js
Labels: enhancement, hacktoberfest-accepted

#121 Adding content_type and icon attribute to Contents
  src/assets/fonts/ArgentumSans-Medium.otf
  src/assets/fonts/ArgentumSans-Regular.otf
  src/assets/fonts/ArgentumSans-SemiBold.otf
  src/assets/fonts/Lovelo-Black.ttf
  src/assets/img/advices/bed.svg
  src/assets/img/advices/doctor.svg
  src/assets/img/advices/germ.svg
  src/assets/img/advices/helpline.svg
  src/assets/img/advices/homework.svg
  src/assets/img/advices/hospital.svg
  src/assets/img/advices/insect.svg
  src/assets/img/advices/mask.svg
  src/assets/img/advices/no-flight.svg
  src/assets/img/advices/protection.svg
  src/assets/img/advices/sick.svg
  src/assets/img/advices/tent.svg
  src/assets/img/advices/thermometer.svg
  src/assets/img/advices/vaccine.svg
  src/assets/img/advices/virus.svg
  src/assets/img/advices/wash.svg
  src/assets/img/logo.png
  src/assets/img/logo.svg
  src/index.css
  src/index.js
  src/pages/Home/components/Contents/index.js
  src/pages/Home/components/Contents/styles.js
  src/sharedComponents/Header/index.js
  src/utils/contentIcons.js
Labels: enhancement

#122 Fix panel height
  src/index.css
  src/pages/Home/index.js
  src/pages/Home/styles.js
  src/pages/Login/Dropdown/styles.js
  src/sharedComponents/Header/styles.js
Labels: bug, enhancement
