Repository ProEpiDesenvolvimento/guardioes-web, pull requests merged in 2020-11, with the labels that each got.

#123 Fix outline in text inputs
  src/pages/Login/Dropdown/styles.js
  src/pages/Login/styles.js
Labels: enhancement

#118 Feature/add manager
  src/actions/index.js
  src/constants/action-types.js
  src/pages/Home/components/Managers/index.js
  src/pages/Home/components/Managers/services/createManager.js
  src/pages/Home/components/Managers/services/deleteManager.js
  src/pages/Home/components/Managers/services/editManager.js
  src/pages/Home/components/Managers/services/getAllManagers.js
  src/pages/Home/components/Managers/styles.js
  src/pages/Home/components/ManagersOld/index.js
  src/pages/Home/index.js
  src/pages/Login/Dropdown/index.js
  src/pages/Login/DropdownComponent/assets/down_arrow.png
  src/pages/Login/DropdownComponent/index.js
  src/pages/Login/DropdownComponent/styles.js
  src/pages/Login/index.js
  src/reducers/user.js
Labels: hacktoberfest-accepted

#125 Loading on table
  package.json
  src/pages/Home/components/ContentBox/Table/index.js
  src/pages/Home/components/ContentBox/Table/styles.js
  src/pages/Home/components/ContentBox/index.js
  src/services/api.js
  src/sharedComponents/Loading/index.js
  src/sharedComponents/Loading/styles.js
Labels: hacktoberfest-accepted

#128 Fix error on reloading page
  src/pages/Home/index.js
  src/pages/Login/index.js
  src/sharedComponents/Header/index.js
Labels: bug

#138 Add Manager permissions
  src/pages/Home/components/Managers/index.js
  src/pages/Home/components/Managers/modelsPermissions.js
  src/pages/Home/components/Managers/styles.js
  src/pages/Home/components/ManagersOld/index.js
Labels: enhancement

#143 Changing texts on dropdown component
  src/sharedComponents/DropdownComponent/index.js
Labels: enhancement

#144 Fixing error that does not show name of the symptoms
  src/pages/Home/components/Syndromes/index.js
Labels: bug

#147 Corrects the app_id when creates objects
  src/pages/Home/components/GroupManagers/index.js
  src/pages/Home/components/Groups/index.js
  src/pages/Home/components/Managers/index.js
  src/pages/Home/components/Symptoms/index.js
  src/pages/Home/components/Syndromes/index.js
Labels: bug

#168 Remove country field on users page
  src/pages/Home/components/Users/index.js
Labels: bug

#166 Fix Syndrome visualization/edition
  src/pages/Home/components/Syndromes/index.js
Labels: bug, enhancement

#173 Adds the permissions to Manager page
  src/pages/Home/components/Managers/index.js
Labels: enhancement

#171 Fix User logged in default Component
  src/pages/Home/components/NavBar/index.js
  src/pages/Home/index.js
Labels: bug, enhancement

#180 Delete confirmation
  src/pages/Home/components/ContentBox/Table/index.js
  src/pages/Home/components/ContentBox/Table/styles.js
  src/pages/Home/components/assets/cancel.svg
  src/pages/Home/components/assets/confirm.svg
Labels: enhancement
